[IMAGEDB]
NAME         = IMAGE_DATAGEN
DATA_DIR     = image_data

IMAGEDB_IP   = 10.4.2.207
IMAGEDB_NAME = IMAGEDB

CLUSTERDB_IP = 10.4.15.131
CLUSTERDB_NAME = CLUSTERED_IMAGEDB

CLUSTERED_WIKI_IMAGEDB=CLUSTERED_WIKI_IMAGEDB
CLUSTERED_WIKI_IMAGEDB_IP=10.4.2.207

SPORTSDB=SPORTSDB
SPORTSDB_IP=10.4.18.183

